<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "in_news"
 *
 * Auto generated by Extension Builder 2013-06-26
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'News',
	'description' => 'News system based on pages',
	'category' => 'plugin',
	'author' => 'Grégory Copin',
	'author_email' => 'gcopin@inouit.com',
	'author_company' => 'Inouit',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.1.0',
	'constraints' => array(
		'depends' => array(
			'extbase' => 'undefined',
			'fluid' => 'undefined',
			'typo3' => '6.1',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>
